version: '3.8'
services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_NAME: file-upload-service
      DB_SCHEMA: file-upload-service
      DB_USER: root
      DB_PASS: root
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:14.5
    environment:
      POSTGRES_DB: file-upload-service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root